# name of the software
name: docs.avchat.net
# current version of the software
version: 3.7.2
# url of the download button
downloadUrl: http://avchat.net
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: Client Area
    url: https://nusofthq.com/c/
    target: _blank
  - title: Discuss AVChat
    url: http://discuss.avchat.net
    target: _blank

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/nusofthq/avchat-documentation
  - title: Client Area
    url: https://nusofthq.com/c/
  - title: Discuss AVChat
    url: http://discuss.avchat.net
# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: false

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: nusofthq
  repo: avchat-documentation

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: nusofthq

# facebook buttons
facebook:
  enabled: true
  profileUrl: https://www.facebook.com/nusoftcompany/


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
